import { Card, Rarity, Faction } from '@/types/Card';

export const mockCards: Card[] = [
  {
    id: '1',
    name: 'Nexus Prime',
    title: 'Mad Scientist of Dimension X-9',
    rarity: Rarity.LEGENDARY,
    faction: Faction.QUANTUM,
    stats: {
      longPosition: 98,
      shortPosition: 85,
      leverage: 70,
      marketIQ: 100,
    },
    description: 'A brilliant interdimensional scientist who can portal between realities. His inventions are legendary, though his methods are... unconventional. Always muttering about quantum mechanics and parallel universes.',
    imageUrl: '/images/cards/nexus-prime.jpg', // Supports .jpg or .png
    marketValue: 10000,
    tradingPair: 'BTC/USD',
    lastTradePrice: 10500,
  },
  {
    id: '2',
    name: 'Zephyr Flux',
    title: 'The Anxious Sidekick',
    rarity: Rarity.EPIC,
    faction: Faction.COSMIC,
    stats: {
      longPosition: 45,
      shortPosition: 75,
      leverage: 60,
      marketIQ: 70,
    },
    description: 'Constantly stressed but somehow always survives interdimensional chaos. His luck stat is off the charts. Panics about everything but never gives up. The universe seems to protect him.',
    imageUrl: '/images/cards/zephyr-flux.jpg',
    marketValue: 3500,
    tradingPair: 'ETH/USD',
    lastTradePrice: 3600,
  },
  {
    id: '3',
    name: 'Voidweaver',
    title: 'Master of Dimensional Rifts',
    rarity: Rarity.LEGENDARY,
    faction: Faction.VOID,
    stats: {
      longPosition: 92,
      shortPosition: 95,
      leverage: 80,
      marketIQ: 88,
    },
    description: 'Controls interdimensional portals with ease. Can travel anywhere, anytime. Time is just a suggestion anyway. Wears a mysterious green glow that pulses with cosmic energy.',
    imageUrl: '/images/cards/voidweaver.jpg',
    marketValue: 8000,
    tradingPair: 'BTC/USD',
    lastTradePrice: 8200,
  },
  {
    id: '4',
    name: 'Quantum Shift',
    title: 'The Reality Bender',
    rarity: Rarity.EPIC,
    faction: Faction.QUANTUM,
    stats: {
      longPosition: 88,
      shortPosition: 90,
      leverage: 65,
      marketIQ: 95,
    },
    description: 'Can phase through dimensions and alter reality at will. Exists in multiple states simultaneously. The most unpredictable fighter in the multiverse. Reality is just a suggestion.',
    imageUrl: '/images/cards/quantum-shift.jpg',
    marketValue: 4500,
    tradingPair: 'ETH/USD',
    lastTradePrice: 4400,
  },
  {
    id: '5',
    name: 'Nexus Helper',
    title: 'The Task Master',
    rarity: Rarity.RARE,
    faction: Faction.NEBULA,
    stats: {
      longPosition: 70,
      shortPosition: 80,
      leverage: 75,
      marketIQ: 85,
    },
    description: 'A helpful AI entity that exists to complete tasks. Gets increasingly frustrated if the task is too difficult. Very enthusiastic at first, then... not so much. But always gets it done.',
    imageUrl: '/images/cards/nexus-helper.jpg',
    marketValue: 1800,
    tradingPair: 'SOL/USD',
    lastTradePrice: 1750,
  },
  {
    id: '6',
    name: 'Stellar Wing',
    title: 'Champion of the Celestial Aviary',
    rarity: Rarity.EPIC,
    faction: Faction.STELLAR,
    stats: {
      longPosition: 90,
      shortPosition: 88,
      leverage: 85,
      marketIQ: 82,
    },
    description: 'A noble warrior from the Celestial Aviary. Loyal friend and fierce fighter. Never forgets a face or a battle. Has seen things that would break lesser beings, but remains steadfast.',
    imageUrl: '/images/cards/stellar-wing.jpg',
    marketValue: 5000,
    tradingPair: 'BTC/USD',
    lastTradePrice: 5100,
  },
  {
    id: '7',
    name: 'Cosmic Rager',
    title: 'The Party Beast',
    rarity: Rarity.RARE,
    faction: Faction.VOID,
    stats: {
      longPosition: 75,
      shortPosition: 85,
      leverage: 70,
      marketIQ: 75,
    },
    description: 'Loves to party across dimensions. Can transform into a massive cosmic beast when needed. Always down for a good time, but don\'t mess with their friends. The life of every interdimensional gathering.',
    imageUrl: '/images/cards/cosmic-rager.jpg',
    marketValue: 2000,
    tradingPair: 'ETH/USD',
    lastTradePrice: 1950,
  },
  {
    id: '8',
    name: 'Dream Stalker',
    title: 'The Nightmare Runner',
    rarity: Rarity.UNCOMMON,
    faction: Faction.VOID,
    stats: {
      longPosition: 65,
      shortPosition: 70,
      leverage: 60,
      marketIQ: 55,
    },
    description: 'A nightmare entity who runs fast through dreams and dimensions. Looks scary but actually pretty nice once you get to know them. Just wants respect and maybe some friends.',
    imageUrl: '/images/cards/dream-stalker.jpg',
    marketValue: 800,
    tradingPair: 'MATIC/USD',
    lastTradePrice: 780,
  },
  {
    id: '9',
    name: 'Fuel Bot',
    title: 'The Hungry Automaton',
    rarity: Rarity.RARE,
    faction: Faction.COSMIC,
    stats: {
      longPosition: 78,
      shortPosition: 65,
      leverage: 88,
      marketIQ: 72,
    },
    description: 'A robot from a distant planet who runs on cosmic fuel. Hates Mondays, Tuesdays, Wednesdays... basically all days. But good fuel makes everything better. Surprisingly philosophical for a bot.',
    imageUrl: '/images/cards/fuel-bot.jpg',
    marketValue: 1500,
    tradingPair: 'SOL/USD',
    lastTradePrice: 1450,
  },
  {
    id: '10',
    name: 'The Nexus',
    title: 'The Collective Consciousness',
    rarity: Rarity.LEGENDARY,
    faction: Faction.NEBULA,
    stats: {
      longPosition: 95,
      shortPosition: 75,
      leverage: 90,
      marketIQ: 98,
    },
    description: 'A collective consciousness that can assimilate entire planets. Emotionally complex despite being a hive mind. Struggles with relationships but understands the universe better than anyone.',
    imageUrl: '/images/cards/the-nexus.jpg',
    marketValue: 9000,
    tradingPair: 'BTC/USD',
    lastTradePrice: 9200,
  },
  {
    id: '11',
    name: 'Space Sweeper',
    title: 'The Cosmic Janitor',
    rarity: Rarity.COMMON,
    faction: Faction.COSMIC,
    stats: {
      longPosition: 50,
      shortPosition: 55,
      leverage: 60,
      marketIQ: 65,
    },
    description: 'Just a janitor who keeps the cosmos clean. Underestimated but always there when needed. Has seen everything and knows everyone. The unsung hero of the multiverse.',
    imageUrl: '/images/cards/space-sweeper.jpg',
    marketValue: 200,
    tradingPair: 'AVAX/USD',
    lastTradePrice: 190,
  },
  {
    id: '12',
    name: 'Fusion Core',
    title: 'The Experimental Hybrid',
    rarity: Rarity.EPIC,
    faction: Faction.QUANTUM,
    stats: {
      longPosition: 85,
      shortPosition: 75,
      leverage: 80,
      marketIQ: 88,
    },
    description: 'A genetic fusion experiment gone right... or wrong? Conflicted between different natures. Struggles with identity but fights for what\'s right... sometimes. A walking contradiction.',
    imageUrl: '/images/cards/fusion-core.jpg',
    marketValue: 4000,
    tradingPair: 'ETH/USD',
    lastTradePrice: 4100,
  },
];
